//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormz.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebFormz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Call stored procedure to set Action status to &quot;A&quot;
        ///protected override void OnLoad(EventArgs e)
        ///    {
        ///        if (Request.QueryString.Get(&quot;iFormSubmissionKey&quot;) != null)
        ///        {
        ///            try
        ///            {
        ///                using (var server = Asi.Data.DataServer.NewDataServer())
        ///                {
        ///                    server.BeginTransaction();
        ///                    var procedureName = &quot;dbo.sp_CPSBC_CaseActionUpdateCaseNum&quot;; 
        ///                    server.ExecuteNonQuery(System.Data.CommandType.Stored [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActionA {
            get {
                return ResourceManager.GetString("ActionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Call stored procedure to set Action Status to &quot;C&quot; (complete)
        ///protected override void OnLoad(EventArgs e)
        ///    {
        ///        if (Request.QueryString.Get(&quot;iFormSubmissionKey&quot;) != null)
        ///        {
        ///            try
        ///            {
        ///                using (var server = Asi.Data.DataServer.NewDataServer())
        ///                {
        ///                    server.BeginTransaction();
        ///                    var param = new List&lt;Asi.Data.DataParameter&gt; { new Asi.Data.DataParameter(&quot;submissionkey&quot;, Request.QueryString.Get
        ///
        ///(&quot;iFor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActionC {
            get {
                return ResourceManager.GetString("ActionC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Call stored procedure to set case status to &quot;New&quot;
        ///protected override void OnLoad(EventArgs e)
        ///    {
        ///        if (Request.QueryString.Get(&quot;iFormSubmissionKey&quot;) != null)
        ///        {
        ///            try
        ///            {
        ///                using (var server = Asi.Data.DataServer.NewDataServer())
        ///                {
        ///                    server.BeginTransaction();
        ///                    var param = new List&lt;Asi.Data.DataParameter&gt; { new Asi.Data.DataParameter(&quot;submissionkey&quot;, Request.QueryString.Get
        ///
        ///(&quot;iFormSubmission [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActionN {
            get {
                return ResourceManager.GetString("ActionN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;webformz&gt;
        ///  &lt;!--Custom Script 0=None, 1=ActionA, 2=ActionC, 3=ActionN--&gt;
        ///  &lt;item webformzno=&quot;WFZ00015&quot; webformzkey=&quot;DB4A74E8-A6FA-483A-9F9F-E2072C25648D&quot; filepath=&quot;&quot; customjavascript=&quot;0&quot;/&gt;
        ///  &lt;item webformzno=&quot;WFZ00019&quot; webformzkey=&quot;8F598354-FD85-4071-A436-917E3C2DF14B&quot; filepath=&quot;&quot; customjavascript=&quot;0&quot;/&gt;
        ///  &lt;item webformzno=&quot;WFZ00040&quot; webformzkey=&quot;C35AFBAF-4BCE-4A29-AB3E-F571CB886538&quot; filepath=&quot;&quot; customjavascript=&quot;0&quot;/&gt;
        ///  &lt;!--&lt;item webformzno=&quot;WFZ00043&quot; webformzke [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebFormZ {
            get {
                return ResourceManager.GetString("WebFormZ", resourceCulture);
            }
        }
    }
}
